GET http://localhost/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVsaXgiLCJpYXQiOjE2NTIwNTc1OTIsImV4cCI6MTY1MjA1ODE5Mn0.4dlmU6h2UegSBibm3cf2psBKfiYpgnmhDM4jL4RxXO4

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjUxOTkyODQxfQ.uVdwtGwgTBS_ctXAFbF_mq8YquRwD_H4Gk-f2Km863w"
}

###

POST http://localhost/auth/register
Content-Type: application/json

{
  "username": "felix",
  "password": "hello"
}

###

POST http://localhost/auth/login
Content-Type: application/json

{
  "username": "felix",
  "password": "hello"
}

###



POST http://localhost/auth/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiZmVsaXgiLCJpYXQiOjE2NTIwNTc1NDd9.VhVs3l8U8kezLS2zfViK4MNIHDb6i5kc_WkgOaL0piY"
}
