GET http://localhost/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibG9jaHlqIiwiaWF0IjoxNjUyMDAzNjUzLCJleHAiOjE2NTIwMDQyNTN9.4737NA4x5AjT79LG65bBmyEru_LLvbHxiORz3Ih9eAk

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjUxOTkyODQxfQ.uVdwtGwgTBS_ctXAFbF_mq8YquRwD_H4Gk-f2Km863w"
}

###

POST http://localhost/register
Content-Type: application/json

{
  "username": "lochyj",
  "password": "person"
}

###

POST http://localhost/login
Content-Type: application/json

{
  "username": "lochyj",
  "password": "person"
}

###



POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjUxOTkyODQxfQ.uVdwtGwgTBS_ctXAFbF_mq8YquRwD_H4Gk-f2Km863w"
}
